# Runs all tests
name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - dev/develop
      - main
  pull_request:
    branches:
      - dev/develop
      - main

    
    
    
jobs:
  test_linux:
    name: run on linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
      
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build clang-15 clang++-15
          
      - name: Install dependencies
        run: sudo apt-get install -y python3-venv
          
      - name: Build
        run: |
          mkdir build-Release
          cd build-Release
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++-15 -DBUILD_TESTS=ON ..
          cmake --build .
          
      - name: Run tests
        run: |
          cd build-Release
          ctest



  test_windows:
    name: run on windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DBUILD_TESTS=On ..
          cmake --build . --config Release
          
      - name: Run tests
        run: |
          cd build
          ctest -C Release
